#!/bin/bash

# 🧪 Шпаргалка по командам тестирования

echo "🧪 Доступные команды для тестирования:"
echo ""
echo "📦 Установка:"
echo "  npm install"
echo ""
echo "▶️  Запуск тестов:"
echo "  npm test                          # Все тесты"
echo "  npm run test:coverage             # С покрытием кода"
echo "  npm run test:watch                # Watch-режим"
echo "  npm run test:verbose              # С подробным выводом"
echo ""
echo "🎯 Конкретные тесты:"
echo "  npm test dateUtils                # Только dateUtils тесты"
echo "  npm test reminderService          # Только reminderService тесты"
echo "  npm test integration              # Только интеграционные"
echo "  npm test textHelpers              # Только склонения"
echo ""
echo "🔍 Фильтрация:"
echo "  npm test -- --testNamePattern=\"26 числа\"  # Поиск по названию"
echo "  npm test -- --onlyFailures        # Только упавшие"
echo ""
echo "📊 Покрытие:"
echo "  npm run test:coverage             # Генерация отчета"
echo "  open coverage/lcov-report/index.html  # Открыть HTML отчет"
echo ""
echo "🐛 Отладка:"
echo "  node --inspect-brk node_modules/.bin/jest --runInBand"
echo ""
echo "🚀 CI/CD:"
echo "  npm test -- --ci --coverage --maxWorkers=2"
echo ""
